ignoreWorkspaceRootCheck: true

shellEmulator: true
trustPolicy: no-downgrade

packages:
  - packages/*
  - desktop

patchedDependencies:
  autoglm.js@0.0.11: patches/autoglm.js@0.0.11.patch

ignoredBuiltDependencies:
  - esbuild
  - electron
  - sharp
