ignoreWorkspaceRootCheck: true

shellEmulator: true

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - current

packages:
  - packages/*
  - desktop

overrides:
  electron: 33.0.2
  tsdown: 0.19.0
  typescript: 5.6.3
  vite: 5.4.21

ignoredBuiltDependencies:
  - esbuild
  - electron
  - sharp
