packages:
  - packages/*
  - desktop

ignoreWorkspaceRootCheck: true

ignoredBuiltDependencies:
  - esbuild
  - electron
  - sharp

patchedDependencies:
  autoglm.js@0.0.10: patches/autoglm.js@0.0.10.patch

shellEmulator: true