packages:
  - packages/*
  - desktop

ignoreWorkspaceRootCheck: true

ignoredBuiltDependencies:
  - esbuild
  - electron
  - sharp

patchedDependencies:
  autoglm.js@0.0.11: patches/autoglm.js@0.0.11.patch

shellEmulator: true
