ignoreWorkspaceRootCheck: true

shellEmulator: true

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - current

packages:
  - packages/*
  - desktop

overrides:
  electron: 33.0.2
  sharp: 0.34.5
  tsdown: 0.19.0
  typescript: 5.6.3
  vite: 5.4.21

patchedDependencies:
  autoglm.js@0.0.11: patches/autoglm.js@0.0.11.patch

ignoredBuiltDependencies:
  - esbuild
  - electron
  - sharp
