shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - vite@5.4.21
  - semver@6.3.1

packages:
  - packages/*
  - desktop

patchedDependencies:
  autoglm.js@0.0.11: patches/autoglm.js@0.0.11.patch

ignoredBuiltDependencies:
  - esbuild
  - electron
  - sharp
