packages:
  - packages/*
  - desktop

ignoreWorkspaceRootCheck: true

patchedDependencies:
  autoglm.js@0.0.11: patches/autoglm.js@0.0.11.patch

ignoredBuiltDependencies:
  - esbuild
  - electron
  - sharp

shellEmulator: true
