export default {
  label: 'preferences.device.name',
  field: 'scrcpy',
  children: {
    screenOffTimeout: {
      label: 'preferences.device.screenOffTimeout.name',
      field: '--screen-off-timeout',
      type: 'InputNumber',
      value: undefined,
      placeholder: 'preferences.device.screenOffTimeout.placeholder',
      tips: 'preferences.device.screenOffTimeout.tips',
      append: 's',
    },
    stayAwake: {
      label: 'preferences.device.stayAwake.name',
      field: '--stay-awake',
      type: 'Switch',
      value: undefined,
      unset: [false],
      placeholder: 'preferences.device.stayAwake.placeholder',
      tips: 'preferences.device.stayAwake.tips',
    },
    keepActive: {
      label: 'preferences.device.keepActive.name',
      field: '--keep-active',
      type: 'Switch',
      value: undefined,
      unset: [false],
      placeholder: 'preferences.device.keepActive.placeholder',
    },
    turnScreenOff: {
      label: 'preferences.device.turnScreenOff.name',
      field: '--turn-screen-off',
      type: 'Switch',
      value: undefined,
      unset: [false],
      placeholder: 'preferences.device.turnScreenOff.placeholder',
    },
    powerOffOnClose: {
      label: 'preferences.device.powerOffOnClose.name',
      field: '--power-off-on-close',
      type: 'Switch',
      value: undefined,
      unset: [false],
      placeholder: 'preferences.device.powerOffOnClose.placeholder',
    },
    noPowerOn: {
      label: 'preferences.device.noPowerOn.name',
      field: '--no-power-on',
      type: 'Switch',
      value: undefined,
      unset: [false],
      placeholder: 'preferences.device.noPowerOn.placeholder',
      tips: 'preferences.device.noPowerOn.tips',
    },
    showTouches: {
      label: 'preferences.device.showTouches.name',
      field: '--show-touches',
      type: 'Switch',
      value: undefined,
      unset: [false],
      placeholder: 'preferences.device.showTouches.placeholder',
      tips: 'preferences.device.showTouches.tips',
    },
  },
}
