export default {
  label: 'preferences.audio.name',
  field: 'scrcpy',

  children: {
    noAudio: {
      label: 'preferences.audio.disableAudio.name',
      field: '--no-audio',
      type: 'Switch',
      value: undefined,
      unset: [false],
      placeholder: 'preferences.audio.disableAudio.placeholder',
      tips: 'preferences.audio.disableAudio.tips',
    },
    audioDup: {
      label: 'preferences.audio.audioDup.name',
      field: '--audio-dup',
      type: 'Switch',
      value: undefined,
      unset: [false],
      placeholder: 'preferences.audio.audioDup.placeholder',
      tips: 'preferences.audio.audioDup.tips',
    },
    audioSource: {
      label: 'preferences.audio.audioSource.name',
      field: '--audio-source',
      type: 'Select',
      value: undefined,
      placeholder: 'preferences.audio.audioSource.placeholder',
      tips: 'preferences.audio.audioSource.tips',
      options: [
        { label: 'default', value: '', message: 'preferences.audio.audioSource.output' },
        { label: 'playback', value: 'playback', message: 'preferences.audio.audioSource.playback' },
        { label: 'mic', value: 'mic', message: 'preferences.audio.audioSource.mic' },
        { label: 'mic-unprocessed', value: 'mic-unprocessed', message: 'preferences.audio.audioSource.mic-unprocessed' },
        { label: 'mic-camcorder', value: 'mic-camcorder', message: 'preferences.audio.audioSource.mic-camcorder' },
        { label: 'mic-voice-recognition', value: 'mic-voice-recognition', message: 'preferences.audio.audioSource.mic-voice-recognition' },
        { label: 'mic-voice-communication', value: 'mic-voice-communication', message: 'preferences.audio.audioSource.mic-voice-communication' },
        { label: 'voice-call', value: 'voice-call', message: 'preferences.audio.audioSource.voice-call' },
        { label: 'voice-call-uplink', value: 'voice-call-uplink', message: 'preferences.audio.audioSource.voice-call-uplink' },
        { label: 'voice-call-downlink', value: 'voice-call-downlink', message: 'preferences.audio.audioSource.voice-call-downlink' },
        { label: 'voice-performance', value: 'voice-performance', message: 'preferences.audio.audioSource.voice-performance' },
      ],
    },
    audioCode: {
      hidden: 'global',
      label: 'preferences.audio.audioCode.name',
      field: '--audio-code',
      customized: true,
      type: 'AudioCodecSelect',
      value: undefined,
      placeholder: 'preferences.audio.audioCode.placeholder',
      options: [
        {
          label: 'opus & c2.android.opus.encoder',
          value: 'opus & c2.android.opus.encoder',
        },
        {
          label: 'aac & c2.android.aac.encoder',
          value: 'aac & c2.android.aac.encoder',
        },
        {
          label: 'aac & OMX.google.aac.encoder',
          value: 'aac & OMX.google.aac.encoder',
        },
        { label: 'raw', value: 'raw' },
      ],
    },
    audioCodec: {
      hidden: true,
      field: '--audio-codec',
      value: undefined,
    },
    audioEncoder: {
      hidden: true,
      field: '--audio-encoder',
      value: undefined,
    },
    audioBitRate: {
      label: 'preferences.audio.audioBitRate.name',
      field: '--audio-bit-rate',
      type: 'Input',
      value: undefined,
      placeholder: 'preferences.audio.audioBitRate.placeholder',
      append: 'bps',
    },
    audioBuffer: {
      label: 'preferences.audio.audioBuffer.name',
      field: '--audio-buffer',
      type: 'InputNumber',
      value: undefined,
      placeholder: 'preferences.audio.audioBuffer.placeholder',
      append: 'ms',
    },
    audioOutputBuffer: {
      label: 'preferences.audio.audioOutputBuffer.name',
      field: '--audio-output-buffer',
      type: 'InputNumber',
      value: undefined,
      placeholder: 'preferences.audio.audioOutputBuffer.placeholder',
      append: 'ms',
    },
  },
}
