export default {
  label: 'preferences.window.name',
  field: 'scrcpy',

  children: {
    windowWidth: {
      hidden: true,
      label: 'preferences.window.size.width',
      field: '--window-width',
      type: 'InputNumber',
      value: undefined,
      placeholder: 'preferences.window.size.width.placeholder',
      tips: 'preferences.window.size.width.tips',
    },
    windowHeight: {
      hidden: true,
      label: 'preferences.window.size.height',
      field: '--window-height',
      type: 'InputNumber',
      value: undefined,
      placeholder: 'preferences.window.size.height.placeholder',
      tips: 'preferences.window.size.height.tips',
    },
    windowX: {
      hidden: true,
      label: 'preferences.window.position.x',
      field: '--window-x',
      type: 'InputNumber',
      value: undefined,
      placeholder: 'preferences.window.position.x.placeholder',
    },
    windowY: {
      hidden: true,
      label: 'preferences.window.position.y',
      field: '--window-y',
      type: 'InputNumber',
      value: undefined,
      placeholder: 'preferences.window.position.y.placeholder',
    },
    windowBorderless: {
      label: 'preferences.window.borderless.name',
      field: '--window-borderless',
      type: 'Switch',
      value: undefined,
      unset: [false],
      placeholder: 'preferences.window.borderless.placeholder',
    },
    fullscreen: {
      label: 'preferences.window.fullscreen.name',
      field: '--fullscreen',
      type: 'Switch',
      value: undefined,
      unset: [false],
      placeholder: 'preferences.window.fullscreen.placeholder',
    },
    alwaysOnTop: {
      label: 'preferences.window.alwaysOnTop.name',
      field: '--always-on-top',
      type: 'Switch',
      value: undefined,
      unset: [false],
      placeholder: 'preferences.window.alwaysOnTop.placeholder',
    },
    disableScreensaver: {
      label: 'preferences.window.disableScreensaver.name',
      field: '--disable-screensaver',
      type: 'Switch',
      value: undefined,
      unset: [false],
      placeholder: 'preferences.window.disableScreensaver.placeholder',
    },
    backgroundColor: {
      label: 'preferences.window.backgroundColor.name',
      field: '--background-color',
      type: 'ColorPicker',
      value: undefined,
      placeholder: 'preferences.window.backgroundColor.placeholder',
    },
  },
}
