export { default as controlModule } from './control/index.js'
export { default as copilotModule } from './copilot/index.js'
export { default as explorerModule } from './explorer/index.js'
export { default as mainModule } from './main/index.js'
export { default as terminalModule } from './terminal/index.js'
